### ISSUE TITLE
Need to uninstall old package before install new version？

### ISSUE THREAD

**Issue by starxn** [TAMU-AML/DSWE-Package#4]
Hi, I tried to intall the latest version 1.3.3 by 

     remotes::install_github("TAMU-AML/DSWE-Package@v1.3.3"), 

the installation run well, but when it ended,  the package version number displayed in RStudio package window  was still 1.3.1.  Maybe the old package should be uninstalled first? Thanks.

**Comment by abhinavprakash2006** [comment]
There is no need to uninstall the old version. It should be updated automatically. 
Try checking the package version through the command: `packageVersion(DSWE)`
You can also try restarting `R` after installation.

Also, you may try the command to install the latest version:
`source("https://raw.githubusercontent.com/TAMU-AML/DSWE-Package/development/.bin_install_script/source_install.R")`

Let us know if that helps.

**Comment by starxn** [comment]
Yes, the version became the latest one after restart R. Thanks. 


--------------------------------


----- 原始邮件 -----
发件人：Abhinav Prakash <notifications@github.com>
收件人：TAMU-AML/DSWE-Package <DSWE-Package@noreply.github.com>
抄送人：starxn <liuxin_nus@sina.com>,  Author <author@noreply.github.com>
主题：Re:_[TAMU-AML/DSWE-Package]_Need_to_uninstall_old_package_before_install_new_version？_(#4)
日期：2020年06月02日 09点55分


There is no need to uninstall the old version. It should be updated automatically.

Try checking the package version through the command: packageVersion(DSWE)

You can also try restarting R after installation.
Also, you may try the command to install the latest version:

source("https://raw.githubusercontent.com/TAMU-AML/DSWE-Package/development/.bin_install_script/source_install.R")
Let us know if that helps.
